version: '3.8'

services:
  # Development service
  mikrogrup-itbot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    profiles:
      - dev

  # Production service  
  mikrogrup-itbot-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    profiles:
      - prod

  # Production with custom port
  mikrogrup-itbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
        - VITE_OPENAI_MODEL=${VITE_OPENAI_MODEL}
        - VITE_AZURE_CLIENT_ID=${VITE_AZURE_CLIENT_ID}
        - VITE_AZURE_TENANT_ID=${VITE_AZURE_TENANT_ID}
        - VITE_AZURE_REDIRECT_URI=${VITE_AZURE_REDIRECT_URI}
    ports:
      - "${PORT:-3000}:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    restart: unless-stopped 